"""Make style column non-nullable

Revision ID: 223c443aea63
Revises: 7bbea6b32824
Create Date: 2025-04-24 18:44:56.763067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '223c443aea63'
down_revision: Union[str, None] = '7bbea6b32824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('releases', 'style',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('releases', 'style',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
