"""Rename track_artist_association to track_artist

Revision ID: 7884c6161b8b
Revises: cc1378fb2079
Create Date: 2025-06-11 17:07:24.796137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7884c6161b8b'
down_revision: Union[str, None] = 'cc1378fb2079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('track_artist_association', 'track_artist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('track_artist', 'track_artist_association')
    # ### end Alembic commands ###
