"""Add style column to releases

Revision ID: 7bbea6b32824
Revises: 
Create Date: 2025-04-24 18:19:21.925812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bbea6b32824'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'artists', ['id'])
    op.create_unique_constraint(None, 'collections', ['id'])
    op.add_column('releases', sa.Column('style', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'tracks', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'tracks', type_='unique')
    op.drop_column('releases', 'style')
    op.drop_constraint(None, 'collections', type_='unique')
    op.drop_constraint(None, 'artists', type_='unique')
    # ### end Alembic commands ###
