"""Add updated_at to background_jobs

Revision ID: 7cc484db2c65
Revises: b4a8f9f2d1c3
Create Date: 2025-07-14 15:03:00.175316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cc484db2c65'
down_revision: Union[str, None] = 'b4a8f9f2d1c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('background_jobs', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('background_jobs', 'updated_at')
    # ### end Alembic commands ###
